server:
  port: 80

spring:
  application:
    name: cloud-consumer-order80
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  #当前数据源操作类型
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: root
  freemarker:
    cache: false

eureka:
  client:
    register-with-eureka: true # 像eureka注册中心注册
    fetch-registry: true # 扫描服务
    service-url:
#      defaultZone: http://localhost:7001/eureka/ # 需要注册的具体服务
      defaultZone: http://server7002:7002/eureka/, http://service7001:7001/eureka/  #集群注册
  instance:
    instance-id: order80 #计算机名
    prefer-ip-address: true  #显示ip地址