server:
  port: 7002

eureka:
  instance:
    hostname: server7002
  client:
    fetch-registry: false   #不像注册中心注册自己
    register-with-eureka: false  #表示自己是注册中心，只负责维护服务，不检索服务
    service-url:
      defaultZone: http://server7001:7001/eureka/  #注册eureka服务集群