server:
  port: 9002

spring:
  application:
    name: cloud-provider-payment
  cloud:
    nacos:
      discovery: #集群注册时可以用逗号将多个服务分隔也可以直接添加nginx配置的域名
        server-addr: 139.224.49.74:8090  #阿里云上面集群配置

