server:
  port: 80
spring:
  application:
    name: my-loadbalance-consumer
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://server7002:7002/eureka/, http://service7001:7001/eureka/
  instance:
    prefer-ip-address: true
    instance-id: loadbalance-consumer
