server:
  port: 8802

spring:
  application:
    name: stream-consumer
  cloud:
    stream:
      binders: # 在此处配置要绑定的rabbitMQ的服务信息
        defaultRabbit: # 表示定义的名称，用于binding的整合
          type: rabbit # 消息中间件类型
          environment: # 设置rabbitMQ的相关环境配置
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
      bindings:  # 服务的整合处理
        input:  # 这个名字是一个通道的名称
          destination: studyExchange # 表示要使用的exchange名称定义
          content-type: application/json # 设置消息类型，本次为json，文本则设为text/plain
          binder: defaultRabbit # 设置要绑定的消息服务的具体设置
#          group: receive  #设置组，在同一个组中消息消费是抢夺模式的，同时也进行持久化操作
eureka:
  client:
    service-url:
      defaultZone: http://server7001:7001/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    instance-id: receive8802  #id名称
    prefer-ip-address: true  #是否显示IP

